// webview-react/src/pages/blocks/List/useController.tsx
import React, { useEffect } from 'react';
import { useModel } from 'umi';
import { getLocalMaterials } from '@/webview/service';
import useService from './useService';

const useController = () => {
  const service = useService();
  const { model } = service;

  const { refresh, setRefresh } = useModel('tab');

  useEffect(() => {
    getList();
  }, []);
  useEffect(() => {
    if (refresh) {
      getList();
    }
  }, [refresh]);

  const getList = () => {
    getLocalMaterials('blocks')
      .then((data) => {
        model.setMaterials(data);
        model.setOriMaterials(data);
      })
      .finally(() => {
        setRefresh(false);
      });
  };

  return {
    service,
  };
};

export default useController;

// webview-vue-webpack/src/views/snippet/List/useController.tsx
import useRefreshPage from '@/model/refreshPage';
import { getLocalMaterials } from '@/vscode/service';
import { onMounted, watch } from 'vue';
import useService from './useService';
const useController = () => {
  const { refresh } = useRefreshPage();

  const service = useService();
  const { model } = service;

  onMounted(() => {
    fetchData();
  });

  watch(refresh, () => {
    fetchData();
  });

  const fetchData = () => {
    getLocalMaterials('snippets').then(res => {
      model.initModel(res);
    });
  };

  return {
    service,
  };
};

export default useController;
