// webview-vue-webpack/src/views/snippet/Detail/index.tsx
import { computed, defineComponent } from 'vue';
import { Form, Button, Dropdown, message } from 'ant-design-vue';
import { DownOutlined } from '@ant-design/icons-vue';
import useController from './useController';
import CodeMirror from '@/components/CodeMirror';
import JsonToTs from '@/components/JsonToTs';
import YapiModal from '@/components/YapiModal';
import { genCodeBySnippetMaterial } from '@/vscode/service';
import router from '@/router';

export default defineComponent({
  setup() {
    const controller = useController();
    const { service } = controller;
    const { model } = service;

    const modelJson = computed(() =>
      JSON.stringify(model.selectedMaterial.data.model, null, 2),
    );
    return () => (
      <div>
        <Form layout="vertical">
          <Form.Item label="模板">
            <CodeMirror
              domId="template"
              lint
              value={model.selectedMaterial.data.template}
              onChange={value => {
                model.selectedMaterial.data.template = value;
              }}
            />
          </Form.Item>
          <Form.Item label="模板数据">
            <CodeMirror
              domId="model"
              lint
              value={JSON.stringify(model.selectedMaterial.data.model, null, 2)}
              onChange={value => {
                model.selectedMaterial.data.model = JSON.parse(value);
              }}
            />
          </Form.Item>
          <Form.Item>
            <Dropdown overlay={controller.menu}>
              <a onClick={e => e.preventDefault()}>
                更多功能 <DownOutlined />
              </a>
            </Dropdown>
            &nbsp;&nbsp;
            <Button
              type="primary"
              size="small"
              onClick={() => {
                genCodeBySnippetMaterial({
                  model: model.selectedMaterial.data.model,
                  template: model.selectedMaterial.data.template,
                }).then(() => {
                  message.success('生成成功');
                });
              }}
            >
              生成代码
            </Button>
          </Form.Item>
        </Form>
        <div style={{ textAlign: 'center', width: '100%' }}>
          <Button
            shape="round"
            onClick={() => {
              router.push('/snippets');
            }}
            style={{ width: '50%' }}
          >
            返回
          </Button>
        </div>
        <JsonToTs
          visible={model.dialogVisible.jsonToTs}
          json={modelJson.value}
          onOk={typeCode => {
            model.selectedMaterial.data.model = {
              ...model.selectedMaterial.data.model,
              type: typeCode,
            };
            model.dialogVisible.jsonToTs = false;
          }}
          onCancel={() => {
            model.dialogVisible.jsonToTs = false;
          }}
        />
        <YapiModal
          visible={model.dialogVisible.yapi}
          onOk={m => {
            model.dialogVisible.yapi = false;
            model.selectedMaterial.data.model = {
              ...model.selectedMaterial.data.model,
              ...(m as object),
            };
          }}
          onCancel={() => {
            model.dialogVisible.yapi = false;
          }}
        />
      </div>
    );
  },
});

// webview-react/src/pages/blocks/Detail/index.tsx
import React from 'react';
import { Button, message, Form, Space, Dropdown } from 'antd';
import { DownOutlined } from '@ant-design/icons';
import FormRender from 'form-render/lib/antd';
import { history } from 'umi';
import YapiModal from '@/components/YapiModal';
import SelectDirectory from '@/components/SelectDirectory';
import CodeMirror from '@/components/CodeMirror';
import JsonToTs from '@/components/JsonToTs';
import useController from './useController';
import { genCodeByBlockMaterial } from '@/webview/service';

export default () => {
  const controller = useController();
  const { service } = controller;
  const { model } = service;

  return (
    <div>
      <Form layout="vertical">
        {/* <Form.Item
          label="模板 Schema"
          style={{ display: model.selectedMaterial.path ? 'flex' : 'none' }}
        >
          <CodeMirror
            domId="schemaCodeMirror"
            lint
            value={JSON.stringify(model.selectedMaterial.schema, null, 2)}
            onChange={value => {
              model.setSelectedMaterial(s => {
                return {
                  ...s,
                  schema: JSON.parse(value),
                };
              });
            }}
          />
        </Form.Item> */}
        {Object.keys(model.selectedMaterial.schema).length > 0 && (
          <Form.Item label="Schema 表单">
            <div style={{ padding: '24px' }}>
              <FormRender
                schema={model.selectedMaterial.schema}
                formData={model.formData}
                onChange={model.setData}
                showValidate={false}
              />
              <br></br>
              <Space>
                <Button
                  type="primary"
                  size="small"
                  onClick={() => {
                    model.setSelectedMaterial(s => {
                      return {
                        ...s,
                        model: model.formData,
                      };
                    });
                  }}
                >
                  重新生成模板数据
                </Button>
              </Space>
            </div>
          </Form.Item>
        )}
        <Form.Item
          label="模板数据"
          style={{ display: model.selectedMaterial.path ? 'flex' : 'none' }}
        >
          <CodeMirror
            domId="modelCodeMirror"
            lint
            value={JSON.stringify(model.selectedMaterial.model, null, 2)}
            onChange={value => {
              model.setSelectedMaterial(s => {
                return {
                  ...s,
                  model: JSON.parse(value),
                };
              });
            }}
          />
          <br></br>
          <Space>
            <Dropdown overlay={controller.menu}>
              <a
                className="ant-dropdown-link"
                onClick={e => e.preventDefault()}
              >
                更多功能 <DownOutlined />
              </a>
            </Dropdown>
            <Button
              type="primary"
              size="small"
              onClick={() => {
                model.setDirectoryModalVsible(true);
              }}
            >
              生成代码
            </Button>
          </Space>
        </Form.Item>
      </Form>
      <div style={{ textAlign: 'center', width: '100%' }}>
        <Button
          shape="round"
          onClick={() => {
            history.push('/blocks');
          }}
          style={{ width: '50%' }}
        >
          返回
        </Button>
      </div>
      <YapiModal
        visible={model.yapiModalVsible}
        onOk={m => {
          model.setSelectedMaterial(s => {
            return {
              ...s,
              model: { ...model.selectedMaterial.model, ...m },
            };
          });
          model.setYapiModalVsible(false);
        }}
        onCancel={() => {
          model.setYapiModalVsible(false);
        }}
      />
      <SelectDirectory
        visible={model.directoryModalVsible}
        onCancel={() => {
          model.setDirectoryModalVsible(false);
        }}
        onOk={(path, createPath = []) => {
          model.setDirectoryModalVsible(false);
          genCodeByBlockMaterial({
            material: model.selectedMaterial.name,
            model: model.selectedMaterial.model,
            path: path,
            createPath: createPath,
          }).then(() => {
            message.success('生成成功');
          });
        }}
      />
      <JsonToTs
        visible={model.jsonToTsModalVisble}
        json={model.selectedMaterial}
        onCancel={() => {
          model.setJsonToTsModalVisble(false);
        }}
        onOk={type => {
          model.setSelectedMaterial(s => {
            return {
              ...s,
              model: { ...model.selectedMaterial.model, type: type },
            };
          });
          model.setJsonToTsModalVisble(false);
        }}
      />
    </div>
  );
};
