// webview-vue/src/components/YapiModal/index.tsx
import { defineComponent, PropType, reactive, ref, watch } from 'vue';
import { Modal, Form, Select, Input, message } from 'ant-design-vue';
import { genTemplateModelByYapi, getYapiDomain, getYapiProjects } from '../../vscode/service';

export default defineComponent({
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
    onOk: Function as PropType<(model: unknown) => void>,
    onCancel: Function as PropType<() => void>,
  },
  emits: ['cancel', 'ok'],
  setup(props, context) {
    const projects = reactive<{ data: { name: string; token: string; domain: string }[] }>({
      data: [],
    });
    const domainRef = ref('');
    const formData = reactive<{
      data: {
        token: string;
        id: string;
        typeName: string;
      };
    }>({ data: {} as any });

    watch(
      () => props.visible,
      () => {
        if (props.visible) {
          getYapiDomain().then((res) => {
            domainRef.value = res;
          });
          getYapiProjects().then((res) => {
            projects.data = res;
          });
        }
      },
    );
    const genModel = () => {
      if (!formData.data.token) {
        message.error('请选择项目');
        return;
      }
      if (!formData.data.id) {
        message.error('请输入yapi接口id');
        return;
      }
      genTemplateModelByYapi({
        domain: domainRef.value,
        id: formData.data.id,
        token: formData.data.token,
        typeName: formData.data.typeName ? formData.data.typeName : undefined,
        funName: undefined,
      }).then((model) => {
        formData.data = {} as any;
        context.emit('ok', model);
      });
    };
    return () => (
      <Modal
        title="根据 YAPI 接口追加模板数据"
        visible={props.visible}
        closable={false}
        okText="确定"
        cancelText="关闭"
        onCancel={() => {
          formData.data = {} as any;
          context.emit('cancel');
        }}
        onOk={() => {
          genModel();
        }}
      >
        {() => (
          <Form layout="vertical">
            {() => (
              <>
                <Form.Item label="项目" required>
                  {() => (
                    <Select
                      placeholder="请选择项目"
                      onChange={(value) => {
                        const selected = projects.data.find((s) => s.token === value);
                        formData.data.token = selected!.token;
                        if (selected?.domain) {
                          domainRef.value = selected.domain;
                        }
                      }}
                      value={formData.data.token}
                    >
                      {() => (
                        <>
                          {projects.data.map((s) => {
                            return (
                              <Select.Option value={s.token} key={s.token}>
                                {() => s.name}
                              </Select.Option>
                            );
                          })}
                        </>
                      )}
                    </Select>
                  )}
                </Form.Item>
                <Form.Item label="接口ID" required>
                  {() => (
                    <Input
                      placeholder="输入 yapi 接口ID"
                      value={formData.data.id}
                      onChange={(e) => {
                        const value = e.target.value;
                        formData.data.id = value;
                      }}
                    />
                  )}
                </Form.Item>
                <Form.Item label="类型名称">
                  {() => (
                    <Input
                      placeholder="输入生成的TS类型名称"
                      value={formData.data.typeName}
                      onChange={(e) => {
                        const value = e.target.value;
                        formData.data.typeName = value;
                      }}
                    />
                  )}
                </Form.Item>
              </>
            )}
          </Form>
        )}
      </Modal>
    );
  },
});

// webview-react/src/components/YapiModal/index.tsx
import React, { useEffect, useState } from 'react';
import { Modal, Form, Select, Input } from 'antd';
import { callVscode } from '@/webview';

interface IProps {
  visible: boolean;
  onOk: (model: any) => void;
  onCancel: () => void;
}

const YapiModal: React.FC<IProps> = ({ visible, onCancel, onOk }) => {
  const [projects, setProjects] = useState<
    { name: string; token: string; domain: string }[]
  >([]);
  const [domain, setDomain] = useState('');
  const [formData, setFormData] = useState<{
    token: string;
    id: string;
    typeName: string;
  }>({} as any);
  useEffect(() => {
    if (visible) {
      callVscode({ cmd: 'getYapiDomain' }, data => {
        setDomain(data);
      });
      callVscode({ cmd: 'getYapiProjects' }, data => {
        setProjects(data);
      });
    }
  }, [visible]);
  const genModel = () => {
    callVscode(
      {
        cmd: 'genTemplateModelByYapi',
        data: {
          domain: domain,
          id: formData.id,
          token: formData.token,
          typeName: formData.typeName ? formData.typeName : undefined,
          funName: undefined,
        },
      },
      model => {
        setFormData({} as any);
        onOk(model);
      },
    );
  };
  return (
    <Modal
      title="根据 YAPI 接口追加模板数据"
      visible={visible}
      closable={false}
      okText="确定"
      cancelText="关闭"
      onCancel={() => {
        setFormData({} as any);
        onCancel();
      }}
      onOk={() => {
        genModel();
      }}
    >
      <Form layout="vertical">
        <Form.Item label="项目" required>
          <Select
            placeholder="请选择项目"
            onChange={value => {
              const selected = projects.find(s => s.token === value);
              setFormData(s => {
                return {
                  ...s,
                  token: selected!.token,
                };
              });
              if (selected?.domain) {
                setDomain(selected?.domain);
              }
            }}
            value={formData.token}
          >
            {projects.map(s => {
              return (
                <Select.Option value={s.token} key={s.token}>
                  {s.name}
                </Select.Option>
              );
            })}
          </Select>
        </Form.Item>
        <Form.Item label="接口ID" required>
          <Input
            placeholder="输入 yapi 接口ID"
            value={formData.id}
            onChange={e => {
              const value = e.target.value;
              setFormData(s => {
                return {
                  ...s,
                  id: value,
                };
              });
            }}
          />
        </Form.Item>
        <Form.Item label="类型名称">
          <Input
            placeholder="输入生成的TS类型名称"
            value={formData.typeName}
            onChange={e => {
              const value = e.target.value;
              setFormData(s => {
                return {
                  ...s,
                  typeName: value,
                };
              });
            }}
          />
        </Form.Item>
      </Form>
    </Modal>
  );
};

export default YapiModal;
