// webview-vue/src/components/JsonToTs/index.tsx
import { defineComponent, PropType, reactive, watch } from 'vue';
import { Modal, Form, Input } from 'ant-design-vue';
import CodeMirror from '../CodeMirror';
import { jsonToTs } from '../../vscode/service';

export default defineComponent({
  props: {
    visible: {
      type: Boolean,
      required: true,
    },
    json: {
      type: Object,
      required: true,
    },
    onCancel: {
      type: Function as PropType<() => void>,
      required: true,
    },
    onOk: {
      type: Function as PropType<(typeCode: string) => void>,
      required: true,
    },
  },
  emits: ['cancel', 'ok'],
  setup(props, context) {
    const formData = reactive<{ json: string; type: string; typeName: string }>({
      json: JSON.stringify(props.json, null, 2),
      type: '',
      typeName: '',
    });
    watch(
      () => props.visible,
      () => {
        if (props.visible) {
          formData.json = JSON.stringify(props.json, null, 2);
        }
      },
    );
    watch([() => formData.json, () => formData.typeName], () => {
      if (formData.json && props.visible) {
        jsonToTs({ json: JSON.parse(formData.json), typeName: formData.typeName }).then((res) => {
          formData.type = res;
        });
      }
    });
    return () => (
      <Modal
        visible={props.visible}
        title="JSON TO TS"
        okText="确定"
        cancelText="取消"
        onOk={() => {
          context.emit('ok', formData.type);
        }}
        onCancel={() => {
          context.emit('cancel');
        }}
        maskClosable={false}
      >
        {() => {
          return (
            <Form layout="vertical">
              {() => (
                <>
                  <Form.Item label="json" required>
                    {() => (
                      <CodeMirror
                        domId="jsonCodeMirror"
                        lint
                        value={formData.json}
                        onChange={(value) => {
                          formData.json = value;
                        }}
                      />
                    )}
                  </Form.Item>
                  <Form.Item label="类型名称">
                    {() => (
                      <Input
                        value={formData.typeName}
                        placeholder="输入类型名称"
                        onChange={(e) => {
                          const { value } = e.target;
                          formData.typeName = value;
                        }}
                      />
                    )}
                  </Form.Item>
                  <Form.Item label="TS 接口类型">
                    {() => <CodeMirror domId="typeCodeMirror" value={formData.type} />}
                  </Form.Item>
                </>
              )}
            </Form>
          );
        }}
      </Modal>
    );
  },
});

// webview-react/src/components/JsonToTs/index.tsx
import React, { useEffect, useState } from 'react';
import { Modal, Form, Input } from 'antd';
import CodeMirror from '../CodeMirror';
import { callVscode } from '@/webview';

interface IProps {
  visible: boolean;
  json: object;
  onCancel: () => void;
  onOk: (tsType: string) => void;
}

const JsonToTs: React.FC<IProps> = ({ visible, json, onCancel, onOk }) => {
  const [formData, setFormData] = useState<{
    json: string;
    type: string;
    typeName: string;
  }>({
    json: JSON.stringify(json, null, 2),
    type: '',
    typeName: '',
  });

  useEffect(() => {}, []);

  useEffect(() => {
    if (visible) {
      setFormData(s => {
        return {
          ...s,
          json: JSON.stringify(json, null, 2),
        };
      });
    }
  }, [visible]);

  useEffect(() => {
    if (formData.json && visible) {
      callVscode(
        {
          cmd: 'jsonToTs',
          data: {
            json: JSON.parse(formData.json),
            typeName: formData.typeName,
          },
        },
        (type: string) => {
          setFormData(s => {
            return {
              ...s,
              type: type,
            };
          });
        },
        () => {},
      );
    }
  }, [formData.json, formData.typeName]);

  return (
    <Modal
      visible={visible}
      title="JSON TO TS"
      onCancel={() => {
        onCancel();
      }}
      onOk={() => {
        onOk(formData.type);
      }}
      okText="确定"
      cancelText="取消"
    >
      <Form layout="vertical">
        <Form.Item label="json" required>
          <CodeMirror
            domId="jsonCodeMirror"
            lint
            value={formData.json}
            onChange={value => {
              setFormData(s => {
                return {
                  ...s,
                  json: value,
                };
              });
            }}
          />
        </Form.Item>
        <Form.Item label="类型名称">
          <Input
            value={formData.typeName}
            placeholder="输入类型名称"
            onChange={e => {
              const { value } = e.target;
              setFormData(s => {
                return {
                  ...s,
                  typeName: value,
                };
              });
            }}
          />
        </Form.Item>

        <Form.Item label="TS 接口类型">
          <CodeMirror
            domId="typeCodeMirror"
            value={formData.type}
            onChange={value => {
              setFormData(s => {
                return {
                  ...s,
                  type: value,
                };
              });
            }}
          />
        </Form.Item>
      </Form>
    </Modal>
  );
};

export default JsonToTs;
