// webview-react/src/pages/snippets/Detail/useController.tsx
import React from 'react';
import { getLocalMaterials } from '@/webview/service';
import { useEffect } from 'react';
import { useParams } from 'umi';
import { Menu } from 'antd';
import useService from './useService';

const useController = () => {
  const params = useParams<{ name: string }>();
  const service = useService();
  const { model } = service;

  useEffect(() => {
    getLocalMaterials('snippets').then(data => {
      if (data.length) {
        const selected = data.find((s: any) => s.name === params.name);
        model.setSelectedMaterial(selected!);
        model.setFormData(model.selectedMaterial.model);
      }
    });
  }, []);

  useEffect(() => {
    model.setSelectedMaterial(s => {
      return {
        ...s,
        model: { ...s.model, ...model.formData },
      };
    });
  }, [model.formData]);

  const menu = (
    <Menu>
      <Menu.Item
        onClick={() => {
          model.setJsonToTsModalVisble(true);
        }}
      >
        JSON TO TS
      </Menu.Item>
      <Menu.Item
        onClick={() => {
          model.setYapiModalVsible(true);
        }}
      >
        根据 YAPI 接口追加模板数据
      </Menu.Item>
      <Menu.Item
        onClick={() => {
          model.setTemplateModalVisble(true);
        }}
      >
        编辑模板
      </Menu.Item>
    </Menu>
  );

  return {
    service,
    menu,
  };
};

export default useController;

// webview-vue-webpack/src/views/snippet/Detail/useController.tsx
import { getLocalMaterials } from '@/vscode/service';
import { onMounted } from 'vue';
import { Form, Button, Menu, Dropdown, message } from 'ant-design-vue';
import { useRoute } from 'vue-router';
import useService from './useService';

const useController = () => {
  const route = useRoute();

  const service = useService();
  const { model } = service;

  onMounted(() => {
    const name = route.params['name'];
    getLocalMaterials('snippets').then(res => {
      if (res.length) {
        const selected = res.find(s => s.name === name);
        if (selected) {
          model.selectedMaterial.data = selected;
        }
      }
    });
  });
  const menu = (
    <Menu
      onClick={({ key }) => {
        if (key === 'jsonToJs') {
          model.dialogVisible.jsonToTs = true;
        }
        if (key === 'yapi') {
          model.dialogVisible.yapi = true;
        }
      }}
    >
      <Menu.Item key="jsonToJs">{() => 'JSON TO TS'}</Menu.Item>
      <Menu.Item key="yapi">{() => '根据 YAPI 接口追加模板数据'}</Menu.Item>
    </Menu>
  );

  return {
    service,
    menu,
  };
};

export default useController;
