// webview-react/src/layout/index.tsx
import React from 'react';
import { Layout } from 'antd';
import { history } from 'umi';
import './index.less';
import { useMount } from 'ahooks';
import HeaderControl from '@/components/HeaderControl';

const { Content } = Layout;

const LayoutC: React.FC = ({ children }) => {
  useMount(() => {
    history.push('/snippets');
  });
  return (
    <Layout className="base-layout">
      <Layout className="site-layout">
        <HeaderControl />
        <Content
          className="site-layout-background"
          style={{
            padding: '24px',
            minHeight: 280,
          }}
        >
          {children}
        </Content>
      </Layout>
    </Layout>
  );
};
export default LayoutC;

// webview-vue/src/layout/index.tsx
import { defineComponent, onMounted } from 'vue';
import { RouterView, useRouter } from 'vue-router';
import { Layout } from 'ant-design-vue';
import HeaderControl from '../components/HeaderControl';
import './index.scss';

export default defineComponent({
  name: 'Layout',
  setup() {
    const router = useRouter();
    onMounted(() => {
      router.push({
        path: '/snippets',
      });
    });
    return () => (
      <Layout class="base-layout">
        {() => (
          <>
            <div class="control-wrap">
              <HeaderControl />
            </div>
            <Layout.Content style={{ padding: '24px' }}>{() => <RouterView />}</Layout.Content>
          </>
        )}
      </Layout>
    );
  },
});
