// webview-vue/src/components/HeaderControl/index.tsx
import { defineComponent, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Radio, Menu, Dropdown } from 'ant-design-vue';
import useHeaderControlTab, { Tab, TabOptions } from '../../model/headerControlTab';
import DownloadMaterials from '../DownloadMaterials';

export default defineComponent({
  name: 'HeaderControl',
  setup() {
    const { tab, updateTab } = useHeaderControlTab();
    const router = useRouter();
    const downloadMaterialsVisible = ref(false);
    const MenuList = (
      <Menu
        onClick={({ key }) => {
          if (key === '0') {
            downloadMaterialsVisible.value = true;
          }
        }}
      >
        {() => (
          <>
            <Menu.Item key="0">{() => '下载物料'}</Menu.Item>
            <Menu.Item key="1">{() => '添加代码片段'}</Menu.Item>
          </>
        )}
      </Menu>
    );
    return () => (
      <div>
        <Radio.Group
          buttonStyle="solid"
          value={tab}
          onChange={(e) => {
            const value = e.target.value as Tab;
            if (value !== 'more') {
              updateTab(value);
              router.push({
                path: value,
              });
            }
          }}
        >
          {() => (
            <>
              <Radio.Button value={TabOptions[0]}>{() => '代码片段'}</Radio.Button>
              <Radio.Button value={TabOptions[1]}>{() => '区块'}</Radio.Button>
              <Radio.Button value={TabOptions[2]}>{() => '插件配置'}</Radio.Button>
              <Dropdown>
                {{
                  default: () => <Radio.Button value={TabOptions[3]}>{() => '更多'}</Radio.Button>,
                  overlay: () => MenuList,
                }}
              </Dropdown>
            </>
          )}
        </Radio.Group>
        <DownloadMaterials
          visible={downloadMaterialsVisible.value}
          onOk={() => {
            downloadMaterialsVisible.value = false;
          }}
          onCancel={() => {
            downloadMaterialsVisible.value = false;
          }}
        />
      </div>
    );
  },
});

// webview-react/src/components/HeaderControl/index.tsx
import React, { useState } from 'react';
import { history, useModel } from 'umi';
import { Radio, Menu, Dropdown, message } from 'antd';
import DownloadMaterials from '../DownloadMaterials';
import { refreshIntelliSense } from '@/webview/service';

export default () => {
  const { tab, setTab } = useModel('tab');
  const [downloadMaterialsVisible, setDownloadMaterialsVisible] = useState(
    false,
  );
  const menu = (
    <Menu>
      <Menu.Item
        key="0"
        onClick={() => {
          setDownloadMaterialsVisible(true);
        }}
      >
        下载物料
      </Menu.Item>
      <Menu.Item
        key="1"
        onClick={() => {
          setTab('empty');
          history.push('/snippets/add/10086');
        }}
      >
        添加代码片段
      </Menu.Item>
      <Menu.Item
        key="2"
        onClick={() => {
          refreshIntelliSense().then(() => {
            message.success('刷新成功');
          });
        }}
      >
        刷新代码智能提示
      </Menu.Item>
    </Menu>
  );
  return (
    <div style={{ textAlign: 'center', marginTop: '20px' }}>
      <Radio.Group
        value={tab}
        onChange={e => {
          const { value } = e.target;
          if (value !== 'more') {
            history.push(value);
            setTab(value);
          }
        }}
        buttonStyle="solid"
      >
        <Radio.Button value="/snippets">代码片段</Radio.Button>
        <Radio.Button value="/blocks">区块</Radio.Button>
        <Radio.Button value="/config">插件配置</Radio.Button>
        <Dropdown overlay={menu}>
          <Radio.Button value="more">更多</Radio.Button>
        </Dropdown>
      </Radio.Group>
      <DownloadMaterials
        visible={downloadMaterialsVisible}
        onOk={() => {
          setDownloadMaterialsVisible(false);
        }}
        onCancel={() => {
          setDownloadMaterialsVisible(false);
        }}
      />
    </div>
  );
};
