// webview-react/src/components/CodeMirror/index.tsx
import React, { useEffect, useRef } from 'react';
import * as codemirror from 'codemirror';
require('script-loader!jsonlint');
require('codemirror/mode/javascript/javascript.js');
require('codemirror/addon/lint/lint.js');
//require('codemirror/addon/lint/javascript-lint.js');
require('codemirror/addon/lint/json-lint.js');
require('codemirror/lib/codemirror.css');
require('codemirror/theme/monokai.css');
require('codemirror/addon/lint/lint.css');

interface IProps {
  domId: string;
  onChange?: (value: string) => void;
  defaultValue?: string;
  value?: string;
  mode?: 'application/json' | 'javascript';
  lint?: boolean;
}

const CodeMirror: React.FC<IProps> = ({
  domId,
  onChange,
  defaultValue,
  value = '',
  mode = 'application/json',
  lint = false,
}) => {
  const codeMirrorInstant = useRef<CodeMirror.EditorFromTextArea>();
  useEffect(() => {
    codeMirrorInstant.current = codemirror.fromTextArea(
      document.getElementById(domId) as any,
      {
        value: defaultValue || value,
        //lineNumbers: true,
        mode: mode,
        // gutters: ['CodeMirror-lint-markers'],
        lint: lint,
        theme: 'monokai',
      },
    );
    if (typeof onChange === 'function') {
      codeMirrorInstant.current.on('change', () => {
        const value = codeMirrorInstant.current!.getValue();
        if (mode === 'application/json' && lint) {
          try {
            JSON.parse(value);
            onChange(value);
          } catch (ex) {}
        } else {
          onChange(value);
        }
      });
    }
  }, []);
  useEffect(() => {
    if (value !== codeMirrorInstant.current?.getValue()) {
      codeMirrorInstant.current?.setValue(value);
    }
  }, [value]);
  return <textarea id={domId}></textarea>;
};
export default CodeMirror;

// webview-vue-webpack/src/components/CodeMirror/index.tsx
import { defineComponent, onMounted, PropType, watch } from 'vue';
import codemirror from 'codemirror';
import './jsonlint.js';
import './mode/javascript/javascript.js';
import './addon/lint/lint.js';
//require('codemirror/addon/lint/javascript-lint.js');
import './addon/lint/json-lint.js';
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/monokai.css';
import 'codemirror/addon/lint/lint.css';

export default defineComponent({
  props: {
    domId: {
      type: String,
      required: true,
    },
    onChange: {
      type: Function as PropType<(value: string) => void>,
    },
    defaultValue: {
      type: String,
    },
    value: {
      type: String,
    },
    mode: {
      type: String as PropType<'application/json' | 'javascript'>,
      default: 'application/json',
    },
    lint: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['change'],
  setup(props, context) {
    let codeMirrorInstant: CodeMirror.EditorFromTextArea;
    onMounted(() => {
      codeMirrorInstant = codemirror.fromTextArea(document.getElementById(props.domId) as any, {
        value: props.defaultValue || props.value,
        //lineNumbers: true,
        mode: props.mode,
        // gutters: ['CodeMirror-lint-markers'],
        lint: props.lint,
        theme: 'monokai',
      });
      codeMirrorInstant.on('change', () => {
        const value = codeMirrorInstant.getValue();
        if (props.mode === 'application/json' && props.lint) {
          try {
            JSON.parse(value);
            context.emit('change', value);
          } catch (ex) {
			  console.error(ex)
		  }
        } else {
          context.emit('change', value);
        }
      });
    });
    watch(
      () => props.value,
      () => {
        if (props.value !== codeMirrorInstant.getValue()) {
          codeMirrorInstant.setValue(props.value || '');
        }
      },
    );
    return () => <textarea id={props.domId}></textarea>;
  },
});
